version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: SmartDocs-Postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smartdocs
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: SmartDocs-Rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    container_name: minio_s3
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      - MINIO_ACCESS_KEY= ${MINIO_ACCESS_KEY:-minio}
      - MINIO_SECRET_KEY= ${MINIO_SECRET_KEY:-miniostorage}
      - MINIO_REGION_NAME= ${MINIO_REGION_NAME:-us-east-1}
    command: 
    - server 
    - /data 
    - --console-address 
    - :9001
  redis:
    image: redis:7
    container_name: redis-smartdocs
    ports: 
    - "6379:6379"

  api-service:
    build:
      context: ../../
      dockerfile: services/api-service/Dockerfile
    container_name: smartdocs-api
    ports:
      - "5000:8080"
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - minio

  processing-service:
    build:
      context: ../../
      dockerfile: services/processing-service/Dockerfile
    container_name: smartdocs-processing
    ports:
      - "7001:7001"
    depends_on:
      - rabbitmq
      - redis
